services:
  api:
    build:
      context: .
      dockerfile: project/api/Dockerfile
    hostname: api
    volumes:
      - ./project/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5
  ui:
    build:
      context: .
      dockerfile: project/ui/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy