_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": linux-x86_64
architecture:
    value: resnet50
batch_size:
    value: 128
epochs:
    value: 2
learning_rate:
    value: 0.001
remove_fc:
    value: false
